name: Package and release development builds

on:
  push:
    branches: [ stable ]
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v1
        with:
          # you can specify how much of the commit history you want to fetch,
          # which is useful for controlling the length of the automated changelog
          fetch-depth: 50

      - name: Package and release for Retail
        uses: BigWigsMods/packager@master

      - name: Package and release for Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic
